//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtkK22CNT4Lesson11_2210900033.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NtkCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NtkCategory()
        {
            this.NtkProducts = new HashSet<NtkProduct>();
        }
    
        public int NtkID { get; set; }
        public string NtkCateName { get; set; }
        public Nullable<bool> NtkStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NtkProduct> NtkProducts { get; set; }
    }
}
