//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtkK22CNT4Lesson11_2210900033.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NtkProduct
    {
        public string NtkId2210900033 { get; set; }
        public string NtkProName { get; set; }
        public Nullable<int> NtkQty { get; set; }
        public Nullable<double> NtkPrice { get; set; }
        public Nullable<int> NtkCateId { get; set; }
        public Nullable<bool> NtkActive { get; set; }
    
        public virtual NtkCategory NtkCategory { get; set; }
    }
}
