//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtkK22CNT4Lesson12_2210900033.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NguyenTrucKien_2210900033Entities : DbContext
    {
        public NguyenTrucKien_2210900033Entities()
            : base("name=NguyenTrucKien_2210900033Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ntk_SACH> Ntk_SACH { get; set; }
        public virtual DbSet<Ntk_TACGIA> Ntk_TACGIA { get; set; }
    }
}
