//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtkK22CNT4Lesson12_2210900033.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ntk_TACGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ntk_TACGIA()
        {
            this.Ntk_SACH = new HashSet<Ntk_SACH>();
        }
    
        public string Ntk_MaTG { get; set; }
        public string Ntk_TenTG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ntk_SACH> Ntk_SACH { get; set; }
    }
}
