//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtkK22CNT4Lesson12_2210900033.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ntk_SACH
    {
        public string Ntk_MaSach { get; set; }
        public string Ntk_TenSach { get; set; }
        public Nullable<int> Ntk_SoTrang { get; set; }
        public Nullable<int> Ntk_NamXB { get; set; }
        public string Ntk_MaTG { get; set; }
        public Nullable<bool> Ntk_TrangThai { get; set; }
    
        public virtual Ntk_TACGIA Ntk_TACGIA { get; set; }
    }
}
