//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtkK22CNT4Lesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NtkAccount
    {
        public int NtkID { get; set; }
        public string NtkUserName { get; set; }
        public string NtkPassword { get; set; }
        public string NtkFullName { get; set; }
        public string NtkEmail { get; set; }
        public string NtkPhone { get; set; }
        public Nullable<bool> NtkActive { get; set; }
    }
}
