//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtkLesson07Df.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ntkKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ntkKhoa()
        {
            this.NtkSinhVien = new HashSet<NtkSinhVien>();
        }
    
        public string NtkMaKH { get; set; }
        public string NtkTenKH { get; set; }
        public Nullable<bool> NtkTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NtkSinhVien> NtkSinhVien { get; set; }
    }
}
