//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtkLesson07Df.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NtkK22CNT4Lesson07DbEntities : DbContext
    {
        public NtkK22CNT4Lesson07DbEntities()
            : base("name=NtkK22CNT4Lesson07DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ntkKhoa> ntkKhoa { get; set; }
        public virtual DbSet<NtkSinhVien> NtkSinhVien { get; set; }
    }
}
