//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NtkLesson07Df.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NtkSinhVien
    {
        public string NtkMaSV { get; set; }
        public string NtkHoSV { get; set; }
        public string NtkTenSV { get; set; }
        public Nullable<System.DateTime> NtkNgaySinh { get; set; }
        public Nullable<bool> TvcPhai { get; set; }
        public string TvcPhone { get; set; }
        public string NtkEmail { get; set; }
        public string NtkMaKH { get; set; }
    
        public virtual ntkKhoa ntkKhoa { get; set; }
    }
}
