//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lesson08.ntk.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NtkK22CNT4Lesson09DbEntities : DbContext
    {
        public NtkK22CNT4Lesson09DbEntities()
            : base("name=NtkK22CNT4Lesson09DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ntkNtkKetqua> ntkNtkNtkKetquas { get; set; }
        public virtual DbSet<ntkKhoa> ntkNtkKhoas { get; set; }
        public virtual DbSet<ntkMonHoc> ntkNtkMonHocs { get; set; }
        public virtual DbSet<ntkSinhVien> ntkNtkSinhViens { get; set; }
    }
}
