//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lesson08.ntk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ntkNtkKetqua
    {
        public string ntkMaSV { get; set; }
        public string ntkMaMH { get; set; }
        public Nullable<decimal> ntkDiem { get; set; }
        public decimal ntkStt { get; set; }
    
        public virtual ntkMonHoc ntkMonHoc { get; set; }
        public virtual ntkSinhVien ntkSinhVien { get; set; }
    }
}
