//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lesson08.ntk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ntkKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ntkKhoa()
        {
            this.ntkNtkSinhViens = new HashSet<ntkSinhVien>();
        }
    
        public string ntkMaKH { get; set; }
        public string ntkTenKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ntkSinhVien> ntkNtkSinhViens { get; set; }
    }
}
