//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lesson08.ntk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ntkSinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ntkSinhVien()
        {
            this.ntkNtkNtkKetquas = new HashSet<ntkNtkKetqua>();
        }
    
        public string ntkMaSV { get; set; }
        public string ntkHoSV { get; set; }
        public string ntkTenSV { get; set; }
        public Nullable<bool> ntkPhai { get; set; }
        public Nullable<System.DateTime> ntkNgaySinh { get; set; }
        public string ntkNoiSinh { get; set; }
        public string ntkMaKH { get; set; }
        public Nullable<decimal> ntkHocBong { get; set; }
        public Nullable<decimal> ntkDiemTrungBinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ntkNtkKetqua> ntkNtkNtkKetquas { get; set; }
        public virtual ntkKhoa ntkKhoa { get; set; }
    }
}
